/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CookieMonster {
    }
}
declare global {
    interface HTMLCookieMonsterElement extends Components.CookieMonster, HTMLStencilElement {
    }
    var HTMLCookieMonsterElement: {
        prototype: HTMLCookieMonsterElement;
        new (): HTMLCookieMonsterElement;
    };
    interface HTMLElementTagNameMap {
        "cookie-monster": HTMLCookieMonsterElement;
    }
}
declare namespace LocalJSX {
    interface CookieMonster {
        "onConsentResult"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "cookie-monster": CookieMonster;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cookie-monster": LocalJSX.CookieMonster & JSXBase.HTMLAttributes<HTMLCookieMonsterElement>;
        }
    }
}
